"""
Runs every strategy over real price history and scores it honestly. A
strategy only becomes eligible for live paper trading if it clears the bar
on real data - if it doesn't, we say so and drop it, we don't keep it anyway.
"""
from __future__ import annotations

from dataclasses import dataclass

import numpy as np
import pandas as pd

import config
import data_feed
import db
import engine
import strategies


@dataclass
class BacktestResult:
    strategy: str
        symbol: str
            num_trades: int
                win_rate: float
                    avg_win: float
                        avg_loss: float
                            sharpe: float
                                total_return_pct: float
                                    passed: bool
                                        reason: str


                                        def _periods_per_year(df: pd.DataFrame) -> float:
                                            if len(df) < 2:
                                                    return 365.0
                                                        span_seconds = (df["open_time"].iloc[-1] - df["open_time"].iloc[0]).total_seconds()
                                                            if span_seconds <= 0:
                                                                    return 365.0
                                                                        avg_step_seconds = span_seconds / (len(df) - 1)
                                                                            seconds_per_year = 365.25 * 24 * 3600
                                                                                return seconds_per_year / avg_step_seconds


                                                                                def run_backtest(symbol: str, strategy_name: str, df: pd.DataFrame | None = None) -> BacktestResult:
                                                                                    strat_fn = strategies.STRATEGIES[strategy_name]
                                                                                        if df is None:
                                                                                                df = data_feed.get_historical(symbol, config.BACKTEST_LOOKBACK_DAYS)
                                                                                                    df = df.reset_index(drop=True)
                                                                                                    
                                                                                                        position = strat_fn(df)
                                                                                                            fee_rate = engine.fee_rate_for(symbol)
                                                                                                                slip = engine.slippage_bps_for(symbol) / 10_000
                                                                                                                    round_trip_cost = 2 * fee_rate + 2 * slip  # paid on entry and on exit
                                                                                                                    
                                                                                                                        trade_returns = []
                                                                                                                            equity_curve = [1.0]
                                                                                                                                in_trade = False
                                                                                                                                    entry_price = None
                                                                                                                                    
                                                                                                                                        for i in range(1, len(df)):
                                                                                                                                                prev_pos, cur_pos = position.iloc[i - 1], position.iloc[i]
                                                                                                                                                        price = df["close"].iloc[i]
                                                                                                                                                        
                                                                                                                                                                if not in_trade and cur_pos == 1:
                                                                                                                                                                            in_trade = True
                                                                                                                                                                                        entry_price = price
                                                                                                                                                                                                elif in_trade and cur_pos == 0:
                                                                                                                                                                                                            raw_return = (price / entry_price) - 1
                                                                                                                                                                                                                        net_return = raw_return - round_trip_cost
                                                                                                                                                                                                                                    trade_returns.append(net_return)
                                                                                                                                                                                                                                                in_trade = False
                                                                                                                                                                                                                                                            entry_price = None
                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                    # mark equity each bar for Sharpe, using held position's daily move net of nothing
                                                                                                                                                                                                                                                                            # (costs are already booked at trade close in trade_returns)
                                                                                                                                                                                                                                                                                    if in_trade and i > 0:
                                                                                                                                                                                                                                                                                                step_return = (price / df["close"].iloc[i - 1]) - 1
                                                                                                                                                                                                                                                                                                        else:
                                                                                                                                                                                                                                                                                                                    step_return = 0.0
                                                                                                                                                                                                                                                                                                                            equity_curve.append(equity_curve[-1] * (1 + step_return))
                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                if in_trade:
                                                                                                                                                                                                                                                                                                                                        # honestly mark the still-open position to the last real price, but
                                                                                                                                                                                                                                                                                                                                                # don't count it as a completed trade in win-rate stats.
                                                                                                                                                                                                                                                                                                                                                        pass
                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                            num_trades = len(trade_returns)
                                                                                                                                                                                                                                                                                                                                                                if num_trades == 0:
                                                                                                                                                                                                                                                                                                                                                                        return BacktestResult(
                                                                                                                                                                                                                                                                                                                                                                                    strategy_name, symbol, 0, 0.0, 0.0, 0.0, 0.0, 0.0, False,
                                                                                                                                                                                                                                                                                                                                                                                                "no completed trades on this history - cannot judge it, so it does not pass",
                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                            wins = [r for r in trade_returns if r > 0]
                                                                                                                                                                                                                                                                                                                                                                                                                losses = [r for r in trade_returns if r <= 0]
                                                                                                                                                                                                                                                                                                                                                                                                                    win_rate = len(wins) / num_trades
                                                                                                                                                                                                                                                                                                                                                                                                                        avg_win = float(np.mean(wins)) if wins else 0.0
                                                                                                                                                                                                                                                                                                                                                                                                                            avg_loss = float(np.mean(losses)) if losses else 0.0
                                                                                                                                                                                                                                                                                                                                                                                                                                total_return_pct = (equity_curve[-1] - 1) * 100
                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                    equity_series = pd.Series(equity_curve)
                                                                                                                                                                                                                                                                                                                                                                                                                                        period_returns = equity_series.pct_change().dropna()
                                                                                                                                                                                                                                                                                                                                                                                                                                            periods_per_year = _periods_per_year(df)
                                                                                                                                                                                                                                                                                                                                                                                                                                                if period_returns.std(ddof=0) > 0:
                                                                                                                                                                                                                                                                                                                                                                                                                                                        sharpe = float(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    period_returns.mean() / period_returns.std(ddof=0) * np.sqrt(periods_per_year)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        sharpe = 0.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            passed = num_trades >= config.MIN_TRADES_TO_JUDGE and sharpe >= config.MIN_SHARPE_TO_PASS
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if not passed:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if num_trades < config.MIN_TRADES_TO_JUDGE:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    reason = f"only {num_trades} trades on real history - too few to trust"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        reason = f"Sharpe {sharpe:.2f} on real history is below the {config.MIN_SHARPE_TO_PASS} bar"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    reason = f"Sharpe {sharpe:.2f} over {num_trades} real trades clears the bar"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return BacktestResult(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                strategy_name, symbol, num_trades, win_rate, avg_win, avg_loss,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        sharpe, total_return_pct, passed, reason,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def run_all() -> list[BacktestResult]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                results = []
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for symbol in config.CRYPTO_SYMBOLS + config.STOCK_SYMBOLS:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            history = data_feed.get_historical(symbol, config.BACKTEST_LOOKBACK_DAYS)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for strategy_name in strategies.STRATEGIES:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                result = run_backtest(symbol, strategy_name, df=history)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            results.append(result)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        with db.connect() as conn:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        conn.execute(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "INSERT INTO strategy_scores (strategy, symbol, passed, sharpe, win_rate, "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "avg_win, avg_loss, num_trades, scored_at) VALUES (?,?,?,?,?,?,?,?,strftime('%s','now')) "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "ON CONFLICT(strategy, symbol) DO UPDATE SET passed=excluded.passed, "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "sharpe=excluded.sharpe, win_rate=excluded.win_rate, avg_win=excluded.avg_win, "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "avg_loss=excluded.avg_loss, num_trades=excluded.num_trades, scored_at=excluded.scored_at",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        result.strategy, result.symbol, int(result.passed), result.sharpe,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                result.win_rate, result.avg_win, result.avg_loss, result.num_trades,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                db.log_event(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "backtest",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                f"{strategy_name} on {symbol}: {result.reason} "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                f"(win_rate={result.win_rate:.0%}, return={result.total_return_pct:.1f}%)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return results
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    db.init_db()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        results = run_all()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for r in sorted(results, key=lambda x: (-x.passed, x.symbol, x.strategy)):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    status = "PASS" if r.passed else "FAIL"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        f"[{status}] {r.strategy:20s} {r.symbol:10s} trades={r.num_trades:3d} "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    f"win_rate={r.win_rate:.0%} sharpe={r.sharpe:6.2f} return={r.total_return_pct:7.2f}% "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                f"- {r.reason}"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
